package model.entity;
// Generated Jun 23, 2019 3:17:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name="project"
    ,catalog="todoapp"
)
public class Project  implements java.io.Serializable {


     private int projId;
     private User user;
     private String projTitle;
     private String projDesc;
     private Set<Task> tasks = new HashSet<Task>(0);

    public Project() {
    }

	
    public Project(int projId) {
        this.projId = projId;
    }
    public Project(int projId, User user, String projTitle, String projDesc, Set<Task> tasks) {
       this.projId = projId;
       this.user = user;
       this.projTitle = projTitle;
       this.projDesc = projDesc;
       this.tasks = tasks;
    }
   
     @Id 

    
    @Column(name="proj_id", unique=true, nullable=false)
    public int getProjId() {
        return this.projId;
    }
    
    public void setProjId(int projId) {
        this.projId = projId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="proj_title", length=15)
    public String getProjTitle() {
        return this.projTitle;
    }
    
    public void setProjTitle(String projTitle) {
        this.projTitle = projTitle;
    }

    
    @Column(name="proj_desc")
    public String getProjDesc() {
        return this.projDesc;
    }
    
    public void setProjDesc(String projDesc) {
        this.projDesc = projDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="project")
    public Set<Task> getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }




}


